// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3kTU8-_G85RFCI4Xy20be3u3gYaZkuY',
    appId: '1:680976412467:web:b6cecadd7577a711265846',
    messagingSenderId: '680976412467',
    projectId: 'sudirman-guerrilla-gambit',
    authDomain: 'sudirman-guerrilla-gambit.firebaseapp.com',
    storageBucket: 'sudirman-guerrilla-gambit.appspot.com',
    measurementId: 'G-LS2C69887R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNX2GRgXjZ__NW0KiVw1jPWAgLea2Tg58',
    appId: '1:680976412467:android:7ddfd7e899c6422d265846',
    messagingSenderId: '680976412467',
    projectId: 'sudirman-guerrilla-gambit',
    storageBucket: 'sudirman-guerrilla-gambit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR0lHqkA8kOQmTp0UPKUmk5hF3mR6hQxY',
    appId: '1:680976412467:ios:80c6045a387b16dc265846',
    messagingSenderId: '680976412467',
    projectId: 'sudirman-guerrilla-gambit',
    storageBucket: 'sudirman-guerrilla-gambit.appspot.com',
    iosBundleId: 'com.example.sudirmanGuerrillaGambit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR0lHqkA8kOQmTp0UPKUmk5hF3mR6hQxY',
    appId: '1:680976412467:ios:4acd662372166d49265846',
    messagingSenderId: '680976412467',
    projectId: 'sudirman-guerrilla-gambit',
    storageBucket: 'sudirman-guerrilla-gambit.appspot.com',
    iosBundleId: 'com.example.sudirmanGuerrillaGambit.RunnerTests',
  );
}
